POST https://api-finaces.onrender.com/transactions 
Content-Type: application/json


{
  "description": "descrição transação",
  "money": 1000,
  "date": "20022003"
}
###

GET  https://api-finaces.onrender.com/transactions
###


PUT  http://localhost:3333/transactions/a84bd95f-2361-48bd-8e40-d7a7d0bdcdba 
Content-Type: application/json


{
  "description": "danilo",
  "money": 1000,
  "date": "20022003"
}

###

DELETE   https://api-finaces.onrender.com/transactions/a52af8e2-00ab-45b8-a9a9-e90c84340d56